# Generated by Django 2.2.2 on 2020-02-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_five', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user',
            new_name='the_user',
        ),
    ]
